name: Verify
on:
  workflow_dispatch:
  push:
    branches:
      - "**"
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
      - name: Install
        run: npm ci
      - name: Check format
        run: npm run format
      - name: Check lint
        run: npm run lint
      - name: Build
        run: npm run build
